### ISSUE TITLE
Icons and colors don't always show?

### ISSUE THREAD

**Issue by JamzTheMan** [ironmonk88/enhanced-terrain-layer#12]
I'm not sure where the "icons" are suppose to be, I never see them anywhere?

And the "colors" only show if I do not separate out the Obstacles. If I leave the environment and obstacles combined I now see the terrain area change colors.

**Comment by JamzTheMan** [comment]
Update, now noticing, the icons only show IF you leave environment/obstacles combined AND refresh the browser after changing the environment type...

**Comment by ironmonk88** [comment]
I think that was a bit of a miscommunication of how environment is supposed to work.
Obstacle is only ever supposed to accompany an environment.  And when you split the two it wasn't allowing the environment to be an obstacle.
I've changed how things are displayed so that it should make more sense, and will prevent users from picking selections that don't work.
