### ISSUE TITLE
Enhancement: Add Urban Environment

### ISSUE THREAD

**Issue by JamzTheMan** [ironmonk88/enhanced-terrain-layer#15]
Would it be possible to add an Urban environment, and for Obstacles add Furniture (or Structure or something akin?) Something for Stairs, tables, carts, etc, Stairs/inclines are a very typically difficult terrain, not sure if that would be it's own obstacle category or not but just looking for something more urban/man made.

**Comment by ironmonk88** [comment]
Urban environment has been added.  Furniture obstacle has been added.
No pictures yet, but I'll work on it.

I think stairs wouldn't need their own type of terrain.  The purpose of environment is that some classes ignore difficult terrain in certain environments.  So the environment/obstacle value is all about giving a Ruler the information it needs to calculate that. But since there's not a feat or item that lets you ignore the difficult terrain of stairs... there's really no point.
